Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.define "control-plane" do |node|
    node.vm.hostname = "control-plane"
    node.vm.network "private_network", ip: "172.20.20.10"

    node.vm.provider "virtualbox" do |vb|
      vb.name = "rancher-kube-control-plane"
      vb.memory = 4096
      vb.cpus = 2
    end
    node.vm.provision "shell", inline: <<-SHELL
      mkdir -p /etc/rancher/rke2/
      echo "node-ip: 172.20.20.10" > /etc/rancher/rke2/config.yaml
    SHELL
  end

  config.vm.define "worker" do |node|
    node.vm.hostname = "worker"
    node.vm.network "private_network", ip: "172.20.20.11"

    node.vm.provider "virtualbox" do |vb|
      vb.name = "rancher-kube-worker"
      vb.memory = 2048
      vb.cpus = 2
    end
    node.vm.provision "shell", inline: <<-SHELL
      mkdir -p /etc/rancher/rke2/
      echo "node-ip: 172.20.20.11" > /etc/rancher/rke2/config.yaml
    SHELL
  end
end